### ISSUE TITLE
please create tag

### ISSUE THREAD

**Issue by fizwit** [cbg-ethz/smallgenomeutilities#5]
Thanks for creating this software and maintaining it. Could you please create a tag for your project? Creating a tag will also create a release. I ask this to promote reproducible science. 

```
git tag 0.2.1
git push origin 0.2.1
```

https://ropensci.github.io/reproducibility-guide/sections/introduction/

**Comment by sposadac** [comment]
Thanks for the suggestion. See 
https://github.com/cbg-ethz/smallgenomeutilities/releases/tag/0.2.1
